const khodams = [
    { name: "Harimau Putih", meaning: "Kamu kuat dan berani seperti harimau, karena pendahulumu mewariskan kekuatan besar padamu." },
    { name: "Monyet Kekar", meaning: "Kamu lincah dan cerdas, mampu menghadapi berbagai tantangan dengan ketangkasan." },
    { name: "Naga Merah", meaning: "Kamu memiliki kekuatan luar biasa dan kebijaksanaan, seperti naga yang legendaris." },
    { name: "Burung Garuda", meaning: "Kamu bebas dan perkasa, melambangkan kebebasan dan kemuliaan." },
    { name: "Serigala Hitam", meaning: "Kamu setia dan memiliki insting tajam, mampu melindungi diri dan orang lain." },
    { name: "Macan Kumbang", meaning: "Kamu misterius dan kuat, seperti macan yang jarang terlihat tapi selalu waspada." },
    { name: "Kuda Emas", meaning: "Kamu berharga dan kuat, siap untuk berlari menuju kesuksesan." },
    { name: "Elang Biru", meaning: "Kamu memiliki visi yang tajam dan dapat melihat peluang dari jauh." },
    { name: "Harimau Loreng", meaning: "Kamu tangguh dan memiliki kekuatan untuk melindungi dan menyerang." },
    { name: "Gajah Putih", meaning: "Kamu bijaksana dan memiliki kekuatan besar, lambang dari keberanian dan keteguhan hati." },
    { name: "Banteng Sakti", meaning: "Kamu kuat dan penuh semangat, tidak takut menghadapi rintangan." },
    { name: "Ular Raksasa", meaning: "Kamu memiliki kebijaksanaan dan kekuatan yang tak terduga, penuh dengan misteri." },
    { name: "Siluman Ular", meaning: "Kamu cerdik dan mempesona, seperti ular yang penuh tipu muslihat namun memukau." },
    { name: "Lautan Api", meaning: "Kamu penuh semangat dan tak kenal takut, siap menghancurkan rintangan apa pun di depanmu." },
    { name: "Elang Perak", meaning: "Kamu memiliki kekuatan dan kecepatan yang luar biasa, melambangkan kemurnian dan kekuatan." },
    { name: "Macan Hitam", meaning: "Kamu memiliki kekuatan tersembunyi dan selalu siap untuk menyerang dengan penuh kekuatan." },
    { name: "Kepala Naga", meaning: "Kamu memiliki kebijaksanaan dan kekuatan yang megah, seperti kepala naga yang terhormat." },
    { name: "Singa Emas", meaning: "Kamu megah dan penuh kekuatan, melambangkan keberanian dan kepemimpinan yang unggul." },
    { name: "Ikan Koi", meaning: "Kamu penuh dengan ketahanan dan keindahan, mampu melewati tantangan dengan kemuliaan." },
    { name: "Burung Phoenix", meaning: "Kamu mampu bangkit kembali dari segala kesulitan, seperti phoenix yang terlahir kembali dari abu." },
    { name: "Harimau Hitam", meaning: "Kamu memiliki kekuatan misterius dan kemampuan untuk menghadapi berbagai tantangan." },
    { name: "Kuda Laut", meaning: "Kamu memiliki ketahanan dan keunikan, mampu menavigasi tantangan dengan elegan." },
    { name: "Serigala Emas", meaning: "Kamu penuh dengan kekuatan dan keberanian, seperti serigala yang cemerlang dan kuat." },
    { name: "Monyet Sakti", meaning: "Kamu memiliki kecerdasan dan keahlian khusus, seperti monyet yang penuh dengan kemampuan luar biasa." },
    { name: "Kuda Hitam", meaning: "Kamu misterius dan kuat, mampu menembus batas-batas yang ada dengan keberanian." },
    { name: "Kuda Perang", meaning: "Kamu memiliki kekuatan dan keberanian dalam menghadapi pertempuran dan tantangan." },
    { name: "Singa Putih", meaning: "Kamu memiliki kemegahan dan kekuatan yang tiada tara, melambangkan keberanian dan kekuatan." },
    { name: "Harimau Madu", meaning: "Kamu penuh dengan kemauan dan ketahanan, mampu bertahan dalam situasi sulit dengan kekuatan." },
    { name: "Bison Agung", meaning: "Kamu memiliki kekuatan dan stabilitas, seperti bison yang kuat dan tak tergoyahkan." },
    { name: "Naga Hitam", meaning: "Kamu memiliki kekuatan misterius dan magis, melambangkan kebijaksanaan dan kekuatan." },
    { name: "Raja Kuda", meaning: "Kamu memiliki kekuatan dan pengaruh yang besar, seperti raja di dunia kuda." },
    { name: "Serigala Perak", meaning: "Kamu penuh dengan kecerdasan dan keberanian, melambangkan kemampuan untuk memimpin dan melindungi." },
    { name: "Naga Biru", meaning: "Kamu memiliki kekuatan dan kedamaian, seperti naga yang melindungi dan membawa ketenangan." },
    { name: "Elang Emas", meaning: "Kamu memiliki keagungan dan kekuatan, seperti elang yang terbang tinggi dengan cemerlang." },
    { name: "Kuda Putih", meaning: "Kamu memiliki kemurnian dan kekuatan, siap untuk menaklukkan segala rintangan." },
    { name: "Singa Hitam", meaning: "Kamu misterius dan penuh kekuatan, melambangkan keberanian dan dominasi." },
    { name: "Burung Hantu", meaning: "Kamu memiliki kebijaksanaan dan kemampuan untuk melihat kebenaran di balik kegelapan." },
    { name: "Harimau Perak", meaning: "Kamu memiliki kekuatan dan keanggunan, seperti harimau yang bersinar dalam kegelapan." },
    { name: "Naga Perak", meaning: "Kamu memiliki kekuatan magis dan kedamaian, seperti naga yang melindungi dengan kebijaksanaan." },
    { name: "Kuda Merah", meaning: "Kamu penuh semangat dan kekuatan, melambangkan energi dan vitalitas yang tinggi." },
    { name: "Ratu Elang", meaning: "Kamu memiliki kebijaksanaan dan kekuatan, seperti ratu elang yang menguasai langit." },
    { name: "Naga Emas", meaning: "Kamu memiliki kemegahan dan kekuatan luar biasa, seperti naga yang berkilauan." },
    { name: "Raja Serigala", meaning: "Kamu memiliki kepemimpinan dan kekuatan, seperti raja di dunia serigala." },
    { name: "Ikan Mas", meaning: "Kamu memiliki ketenangan dan keindahan, mampu menghadapi arus kehidupan dengan elegan." },
    { name: "Singa Merah", meaning: "Kamu memiliki keberanian dan kekuatan yang menyala, seperti singa merah yang perkasa." },
    { name: "Elang Hitam", meaning: "Kamu memiliki kekuatan dan kecepatan, melambangkan kekuatan yang misterius dan mempesona." },
    { name: "Kepala Ular", meaning: "Kamu memiliki kebijaksanaan dan kekuatan yang luar biasa, seperti kepala ular yang berwibawa." },
    { name: "Kuda Suci", meaning: "Kamu memiliki kemurnian dan kekuatan spiritual, melambangkan kesucian dan kekuatan batin." },
    { name: "Singa Emas", meaning: "Kamu megah dan penuh kekuatan, melambangkan keberanian dan kepemimpinan yang unggul." }
];

