const jodohReasons = [
    "Kalian berdua memiliki kesamaan yang luar biasa dan saling melengkapi.",
    "Hubungan kalian penuh dengan pengertian dan saling mendukung.",
    "Kalian memiliki chemistry yang kuat dan akan saling melengkapi.",
    "Kalian saling memahami satu sama lain tanpa perlu banyak kata.",
    "Kalian berdua selalu menemukan cara untuk membuat satu sama lain tersenyum.",
    "Kalian memiliki tujuan hidup yang sama dan saling mendukung.",
    "Kalian berdua memiliki rasa hormat yang besar satu sama lain.",
    "Kalian bisa saling mengandalkan dalam situasi apapun.",
    "Kalian selalu merasa nyaman dan aman saat bersama.",
    "Kalian berdua selalu tahu bagaimana membuat satu sama lain bahagia.",
    "Kalian memiliki ketertarikan yang sama dan dapat menikmatinya bersama.",
    "Kalian bisa saling melengkapi dalam banyak hal.",
    "Kalian selalu saling mendukung dan memberi semangat.",
    "Kalian berdua memiliki cara yang unik dalam menunjukkan cinta.",
    "Kalian berbagi banyak kenangan indah bersama.",
    "Kalian selalu menemukan cara untuk menyelesaikan masalah bersama.",
    "Kalian saling mengerti dan menerima kekurangan satu sama lain.",
    "Meski berbeda agama, cinta kalian sekuat itu.",
    "Kalian tidak bisa makan siang tanpa memikirkan satu sama lain.",
    "Setiap kali kalian bertemu, ada kembang api di udara."
];

const tidakReasons = [
    "Meskipun kalian baik, tapi kalian berdua mungkin tidak cocok bersama.",
    "Kalian mungkin lebih baik sebagai teman daripada pasangan.",
    "Perbedaan kalian terlalu besar untuk diatasi dalam hubungan romantis.",
    "Kalian mungkin memiliki visi hidup yang berbeda.",
    "Terkadang, cinta tidak cukup untuk membuat hubungan berhasil.",
    "Kalian mungkin tidak dapat saling memberi apa yang kalian butuhkan.",
    "Kalian mungkin akan lebih bahagia dengan orang lain.",
    "Kalian memiliki tujuan hidup yang berbeda.",
    "Perbedaan antara kalian bisa menjadi penghalang besar dalam jangka panjang.",
    "Kalian mungkin terlalu mirip satu sama lain.",
    "Kalian berdua memiliki kepribadian yang sangat berbeda.",
    "Kalian mungkin tidak dapat memenuhi ekspektasi satu sama lain.",
    "Hubungan kalian mungkin penuh dengan konflik.",
    "Kalian mungkin tidak dapat memberikan komitmen yang sama.",
    "Kalian mungkin tidak merasa nyaman satu sama lain dalam jangka panjang.",
    "Kalian memiliki nilai yang berbeda dalam hidup.",
    "Kalian mungkin lebih baik mengejar kebahagiaan masing-masing.",
    "Kalian mungkin tidak dapat mengatasi perbedaan kalian.",
    "Kalian berdua mungkin memiliki prioritas yang berbeda.",
    "Cinta kalian terhalang oleh alasan yang sama sekali tidak masuk akal."
];
